### PR TITLE
support customized edge weight in metis partition

### PR DESCRIPTION
**Pull request by Guangxuan-Xiao**

### CODE REVIEW

**Comment by rusty1s** [comment]
Can you give some description what motivated you to do this PR? I think the current implementation is fine as it is (utilizing `SparseTensor` values as weights in case the user wants to perform weighted clustering), so I'm curious on what you think :)

**Comment by Guangxuan-Xiao** [comment]
Thank you for your reply! I think the current implementation (utilizing `SparseTensor` as weights) is not enough for users to perform weighted clustering, since the `value` attributes will store edge indices in some use cases. For example, in your `ClusterData` implementation, you utilize the `value` field to index edges and get edge indices of partitions. Therefore, users actually cannot perform weighted clustering in this case. 
I suggest setting another optional parameter for users to customize edge weights :)

**Comment by rusty1s** [comment]
Yes, I understand. I always thought that if you want to perform weighted clustering, you can simply set your weights via a new adjacency matrix:
```python
adj = adj.set_value(weight)
```
I will think about it and will probably merge afterwards :)

**Comment by Guangxuan-Xiao** [comment]
Thanks!

**Pull request closed without merging**
