### PR TITLE
add test that fails on my computer but should work

### PR DESCRIPTION
**Pull request by mariogeiger**

### CODE REVIEW

**Comment by mariogeiger** [comment]
are the tests on travis done on cuda?

**Comment by rusty1s** [comment]
Yeah, that is indeed a bug, caused by wrong rowptr computation when values add up to zero. I will look into this.

**Comment by rusty1s** [comment]
Should be fixed in master!

**Comment by mariogeiger** [comment]
great !

**Comment by mariogeiger** [comment]
The mistake was only on cpu?

**Comment by rusty1s** [comment]
yes

**Pull request merged**
