### PR TITLE
torch_sparse.partition supports weighted graphs

### PR DESCRIPTION
**Pull request by bwdeng20**
Test only on Ubuntu18LTS

### CODE REVIEW

**Comment by bwdeng20** [comment]
Need more tests

**Comment by rusty1s** [comment]
You can leave this open while continuing working on it.

**Comment by bwdeng20** [comment]
My first idea is changing the cpp interface 
``` cpp
torch::Tensor partition(torch::Tensor rowptr, torch::Tensor col,int64_t num_parts,bool recursive)
```
to 
``` cpp
torch::Tensor partition(torch::Tensor rowptr, torch::Tensor col,int64_t num_parts, 
torch::optional<torch::Tensor> edge_wgt,bool recursive)
```
, such that `edge_wgt` passed from python interface 
``` python3
   cluster = torch.ops.torch_sparse.partition(rowptr, col, num_parts, edge_wgt, recursive)
```
can be set as None if the graph is unweighted. But due to my lack of Cpp programming skill, I failed to further translate `None` edge_wgt to `NULL` in the evetual invocation of `METIS_PartGraphRecursive`.
 
So I decided to set `edge_wgt` a  all-one long tensor in the case of unweighted graph. This implementation may lead to  unnecessary memory  allocation if `METIS_PartGraphRecursive` doesn't allocate memory in the case of `adjwgt` is NULL.
``` cpp
    METIS_PartGraphRecursive(&nvtxs, &ncon, xadj, adjncy, NULL, NULL, adjwgt,
                             &num_parts, NULL, NULL, NULL, &objval, part_data);
```
As I am eager to implement my research idea, I prefer to  accept this defect.

**Comment by rusty1s** [comment]
You can make use of `torch::optional<torch.Tensor>` for this, and access the values via `tensor.has_value()` and `tensor.value()`.

**Comment by bwdeng20** [comment]
Thx, I will have a try

**Comment by bwdeng20** [comment]
Please review this PR. I'am sorry for the unclear commit info. :smile:

**Comment by rusty1s** [comment]
Thanks, this looks good overall. The only issue I have is that computing `metis_weight` is super expensive and requires huge amount of memory (due to finding `diff.abs().min()`). Is there a more clever way to prevent this? Otherwise, it would be more convenient to only use edge weights in case those are already of integer type. WDYT?

**Comment by bwdeng20** [comment]
How about using `torch.sort` to find `max` and  `min` and the minimum difference ? In this way we can  reduce the  `O(n^2)` space complexity to an acceptable one, with a cost of time complexity increase. And I'am not sure which algorithm the internal implementation  by `torch.sort`  utlizes.

**Comment by rusty1s** [comment]
That sounds better. We should maybe also provide an option to make this optional.

**Comment by bwdeng20** [comment]
I agree with you as it can provide more flexibility.

**Comment by rusty1s** [comment]
Great!

**Comment by bwdeng20** [comment]
Seems done.  Thank you. I had a good time of making these little changes :-) .

**Comment by rusty1s** [comment]
Perfect, I will go through and will merge afterwards.

**Pull request merged**
